### ISSUE TITLE
Using different security margins for collision checking

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-core#200]
Now that classes deriving from `ObstacleUserInterface` handle in an homogeneous way collision checking, I would like to allow users to set different security margins for different collision pairs.
To do so, I propose to add a method `setSecurityMargin` to `ObstacleUserInterface`. this method would take as input a matrix of margins, similarly as what is done for `filterCollisionPairs`.

Any opinion ?

**Comment by jmirabel** [comment]
That is a good idea. I think I had in mind to do something like this and didn't because it wasn't straightforward. I cannot remember the exact reason. Here are some thoughts.

What granularity do we need : body-body or joint-joint ? I believe that we need the body-body granularity. But then, we need a way of indexing both the obstacles and the robot geometries, which aren't in the same pinocchio Model.

Another tricky point is that continuous and discrete collision checking have a very different way of handling the pairs. I don't think this is blocking. It is only making the code harder to write.

**Comment by florent-lamiraux** [comment]
class `BodyPairCollision` has indeed its own `CollisionRequest` as a static variable in method `computeDistanceLowerBound`.
Concerning the granularity, it seems to me that joint-joint would be enough, at least for manipulation planning applications.

**Comment by jmirabel** [comment]
Putting a box on a table requires a null security margin, so between the box and the table. However, in our scenario, we may want to use an arbitrary security margin between that the legs of the table and the box.

**Comment by pFernbach** [comment]
I will be very interested by this too. I'd like to able to define arbitrary security margin between some joint of the robot and the environment.

**Comment by florent-lamiraux** [comment]
Putting a box on a table - at least in our domain of application - is a short motion performed with a precise localization. I think that setting the margin to 0 for the pair (box, environment) is fine.
@nim65s, let us talk about that at the next HPP meeting.

**Comment by florent-lamiraux** [comment]
I think continuous collision checking still needs some refactoring before proceeding further on with issue. I will open another issue.

**Comment by jmirabel** [comment]
@florent-lamiraux I think this is solved by #203, isn't it ?

**Comment by florent-lamiraux** [comment]
Yes.
